export { default as config } from '../../app.config';
export type { AppConfig } from '../../app.config';

export {
	PERMISSION_GROUPS,
	FEATURE_FLAGS,
	PAGINATION_DEFAULTS,
	PermissionKey,
	ROLE_PRIORITY,
	ROLE_LABELS,
	AUTH_ROUTE_PERMISSIONS,
	AUTH_DEFAULT_ROUTES,
	AUTH_PUBLIC_ROUTE_PREFIXES,
	NAVIGATION_ITEMS,
	NAVIGATION_GROUP_LABELS,
	NavigationGroup,
	PIPELINE_PHASE_ORDER,
	PIPELINE_PHASE_LABELS,
	PIPELINE_PHASE_DESCRIPTIONS,
	SOURCE_TYPE_LABELS,
	SOURCE_FILE_EXTENSIONS,
	SOURCE_INTAKE_ACCEPT,
	SOURCE_TYPE_COLORS,
	FACT_STATUS_LABELS,
	FACT_STATUS_COLORS
} from './domain';
export type { PermissionGroup, PermissionRole, NavigationItem } from './domain';
